# Generated by Django 5.1.2 on 2024-10-20 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('users_id', models.ManyToManyField(related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lat', 'lon')},
            },
        ),
    ]
