# Generated by Django 5.1.2 on 2024-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
